### ISSUE TITLE
Which GloVe vector is used?

### ISSUE THREAD

**Issue by supakjk** [nmrksic/counter-fitting#1]
I compared the vector values in glove.txt with corresponding vectors from http://nlp.stanford.edu/projects/glove/. However, for the same words, I couldn't find matching vectors.

Could you let me know where did you obtain the vector values of glove.txt?

Thanks!

 Joo-Kyung Kim

**Comment by nmrksic** [comment]
Hi Joo-Kyung,

Thanks for your interest! I used the Common Crawl version from: http://nlp.stanford.edu/projects/glove/

To be precise, the Common Crawl (840B tokens, 2.2M vocab, cased, 300d vectors, 2.03 GB download) vectors were the one used (as specified in NAACL paper). This collection was then pruned using the limited vocabulary (it's in the GitHub repo, under linguistic_constraints/vocabulary.txt). The values were also rounded to four decimals to make the download size smaller (with four decimals, performance shouldn't be much affected).

Best wishes,
Nikola

**Comment by supakjk** [comment]
For example, the first 10 elements of "fawn" from the glove.txt.zip here is:
-0.0583 0.0314 0.0488 0.0595 -0.0273 -0.0314 0.0512 -0.0192 -0.0798 0.0178 
but those of "fawn" from glove.840B.300d.zip at the Stanford site is 
-0.39673 0.21361 0.33204 0.40462 -0.18555 -0.21382 0.34803 -0.13027 -0.54255 0.12126.

If you did some kind of preprocessing such as normalization or standardization, could you let me know what you did?

Thanks.

 Joo-Kyung

**Comment by nmrksic** [comment]
You are right - the vectors in glove.txt have been normalised (will specify that in the readme file). However, the normalise_word_vectors method (line 132 in counterfitting.py) is always called, regardless of whether the initial vectors are normalised or not. 

Since we use the cosine distance, this makes no difference in the subsequent procedure. I've seen very minor differences in the behaviour of the procedure depending on whether the vectors are re-normalised after each SGD step - the cosine distances between resulting vectors remain pretty much unchanged.

**Comment by supakjk** [comment]
Thank you for the clarification!
